<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="pyqle"
    nsURI="http://pyqle.org" nsPrefix="pyqle">
  <eSubpackages name="agent" nsURI="http://pyqle.org/agent" nsPrefix="agent">
    <eClassifiers xsi:type="ecore:EClass" name="Agent" abstract="true">
      <eOperations name="enableLearning"/>
      <eOperations name="freezeLearning"/>
      <eOperations name="setInitialState"/>
      <eOperations name="choose"/>
      <eOperations name="getActionList"/>
      <eOperations name="applyAction"/>
      <eOperations name="getLastReward"/>
      <eOperations name="act"/>
      <eOperations name="explainValues"/>
      <eOperations name="newEpisode"/>
      <eOperations name="extractDataset"/>
      <eOperations name="getAlgorithm"/>
      <eOperations name="getEnvironment"/>
      <eOperations name="getCurrentState"/>
      <eOperations name="setLastAction"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="learningEnabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="reward" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="currentState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="algorithm"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="universe"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="lastAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="old_state"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ElementaryAgent" eSuperTypes="#//agent/Agent">
      <eOperations name="setSelector"/>
      <eOperations name="setCurrentState"/>
      <eOperations name="applyAction"/>
      <eOperations name="setInitialState"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="filter"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="internalReward" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rank" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Swarm" eSuperTypes="#//agent/Agent">
      <eOperations name="getNAgents"/>
      <eOperations name="add"/>
      <eOperations name="setInitialState"/>
      <eOperations name="newEpisode"/>
      <eOperations name="choose"/>
      <eOperations name="applyAction"/>
      <eOperations name="extractDataset"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nAgents"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementary_agents" upperBound="-1"
          eType="#//agent/Agent"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="composedAction"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="selector" nsURI="http://pyqle.sf.net/selector" nsPrefix="selector">
    <eClassifiers xsi:type="ecore:EClass" name="AbstractMemorySelector">
      <eOperations name="getRewardStore"/>
      <eOperations name="getValue"/>
      <eOperations name="setValue"/>
      <eOperations name="setDecay"/>
      <eOperations name="getDecay"/>
      <eOperations name="setGeometricAlphaDecay"/>
      <eOperations name="setExponentialAlphaDecay"/>
      <eOperations name="setRouletteWheel"/>
      <eOperations name="setEpsilonGreedy"/>
      <eOperations name="setBoltzmann"/>
      <eOperations name="newEpisode"/>
      <eOperations name="learn"/>
      <eOperations name="getChoice"/>
      <eOperations name="rouletteWheelChoice"/>
      <eOperations name="epsilonGreeyChoice"/>
      <eOperations name="boltzmannChoice"/>
      <eOperations name="bestAction"/>
      <eOperations name="toString"/>
      <eOperations name="extractDataset"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memory"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tau" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.5"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.9"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gamma" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.9"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="epsilon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.5"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="generator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="decayAlpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.999999"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alphaDecayPower"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="geometricdecay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rouletteWheel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="epsilonGreedy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boltzmann" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="AbstractQLambdaSelector" eSuperTypes="#//selector/QLearningSelector">
      <eOperations name="reset"/>
      <eOperations name="learn"/>
      <eOperations name="newEpisode"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lambda" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eligibles"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="replace" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="HumanSelector">
      <eOperations name="learn"/>
      <eOperations name="getChoice"/>
      <eOperations name="extractDataset"/>
      <eOperations name="newEpisode"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NNSelector" eSuperTypes="#//selector/AbstractMemorySelector">
      <eOperations name="toString"/>
      <eOperations name="getWeight"/>
      <eOperations name="getSizeOfLayer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="reward"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="PengSelector" eSuperTypes="#//selector/AbstractQLambdaSelector">
      <eOperations name="learn"/>
      <eOperations name="setRouletteWheel"/>
      <eOperations name="setBoltzmann"/>
      <eOperations name="getChoice"/>
      <eOperations name="best"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QLearningIntegerSelector">
      <eOperations name="setThreshold"/>
      <eOperations name="getThreshold"/>
      <eOperations name="randomise"/>
      <eOperations name="getChoice"/>
      <eOperations name="learn"/>
      <eOperations name="bestAction"/>
      <eOperations name="extractDataset"/>
      <eOperations name="newEpisode"/>
      <eOperations name="toString"/>
      <eOperations name="showHistogram"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="generator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="f1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="f2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="f3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="p1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="m1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memory"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="theta" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
          defaultValueLiteral="200"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="QLearningSelector" eSuperTypes="#//selector/AbstractMemorySelector">
      <eOperations name="showHistogram"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="RandomSelector">
      <eOperations name="getChoice"/>
      <eOperations name="learn"/>
      <eOperations name="newEpisode"/>
      <eOperations name="extractDataset"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TDFASelector">
      <eOperations name="setDecay"/>
      <eOperations name="getDecay"/>
      <eOperations name="setGeometricAlphaDecay"/>
      <eOperations name="setExponentialAlphaDecay"/>
      <eOperations name="learn"/>
      <eOperations name="extractDataset"/>
      <eOperations name="newEpisode"/>
      <eOperations name="reset"/>
      <eOperations name="setRouletteWheel"/>
      <eOperations name="setEpsilonGreedy"/>
      <eOperations name="setBoltzmann"/>
      <eOperations name="getChoice"/>
      <eOperations name="epsilonGreedyChoice"/>
      <eOperations name="rouletteWheelChoice"/>
      <eOperations name="boltzmannChoice"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="generator"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="lambda" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.9"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.1"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="gamma" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.9"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="epsilon" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.5"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="decayAlpha" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.999999"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="1.0"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="alphaDecayPower" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.8"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="geometricDecay" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="bestSoFar"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="eligibleTiles"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="rouletteWheel" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="epsilonGreedy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="boltzmann" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="tau" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="0.5"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WatkinsNNSelector" eSuperTypes="#//selector/WatkinsSelector">
      <eOperations name="getWeight"/>
      <eOperations name="sizeOfLayer"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="memory"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WatkinsSelector" eSuperTypes="#//selector/AbstractQLambdaSelector">
      <eOperations name="learn"/>
      <eOperations name="getInternalChoice"/>
      <eOperations name="getChoice"/>
      <eOperations name="reset"/>
      <eOperations name="newEpisode"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actionPrime"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="count" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
          defaultValueLiteral="1.0"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="WinnerSelector">
      <eOperations name="getChoice"/>
      <eOperations name="learn"/>
      <eOperations name="newEpisode"/>
      <eOperations name="extractDataset"/>
    </eClassifiers>
  </eSubpackages>
  <eSubpackages name="environment" nsURI="http://pyqle.org/environment" nsPrefix="environment">
    <eClassifiers xsi:type="ecore:EClass" name="Action"/>
    <eClassifiers xsi:type="ecore:EClass" name="ComposedAction">
      <eOperations name="getNAgents"/>
      <eOperations name="addElementaryAction"/>
      <eOperations name="getAction"/>
      <eOperations name="getAgent"/>
      <eOperations name="copy"/>
      <eOperations name="NNCodingSize"/>
      <eOperations name="NNCoding"/>
      <eOperations name="isNullAction"/>
      <eOperations name="hashCode"/>
      <eOperations name="equals"/>
      <eOperations name="toString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="elementaryAgents" eType="#//agent/ElementaryAgent"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nAgents" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="isNullAction" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Environment">
      <eOperations name="getActionList"/>
      <eOperations name="successorState"/>
      <eOperations name="defaultInitialState"/>
      <eOperations name="getReward"/>
      <eOperations name="isFinal"/>
      <eOperations name="whoWins"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="State">
      <eOperations name="isFinal"/>
      <eOperations name="getActionList"/>
      <eOperations name="modify"/>
      <eOperations name="getReward"/>
      <eOperations name="getWinner"/>
      <eOperations name="copy"/>
      <eOperations name="NNCodingSize"/>
      <eOperations name="NNCoding"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="environment" eType="#//environment/Environment"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ActionList">
      <eOperations name="add"/>
      <eOperations name="getNActions"/>
      <eOperations name="getAction"/>
      <eOperations name="toString"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="actions"/>
      <eStructuralFeatures xsi:type="ecore:EAttribute" name="nActions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="state" eType="#//environment/State"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="ElementaryEnvironment" eSuperTypes="#//environment/Environment">
      <eOperations name="getActionList"/>
      <eOperations name="successorState"/>
      <eOperations name="defaultInitialState"/>
      <eOperations name="getReward"/>
      <eOperations name="isFinal"/>
      <eOperations name="whoWins"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="Filter">
      <eOperations name="filterState"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="NullableAction">
      <eOperations name="copy"/>
      <eOperations name="isNullAction"/>
      <eOperations name="NNCoding"/>
      <eOperations name="NNCodingSize"/>
      <eOperations name="getNullAction"/>
      <eOperations name="setNullAction"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="nullAction"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EClass" name="TileableEnvironment">
      <eOperations name="getTiles"/>
      <eStructuralFeatures xsi:type="ecore:EReference" name="tiles"/>
    </eClassifiers>
    <eClassifiers xsi:type="ecore:EEnum" name="primes">
      <eLiterals name="2" literal=""/>
      <eLiterals name="3" value="1"/>
      <eLiterals name="5" value="2"/>
      <eLiterals name="7" value="3"/>
    </eClassifiers>
  </eSubpackages>
</ecore:EPackage>
