#-------------------------------------------------------------------------------
# Copyright (C) 2007 Richard W. Lincoln
#
# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; version 2 dated June, 1991.
#
# This software is distributed in the hope that it will be useful, but
# WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANDABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the GNU
# General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software Foundation,
# Inc., 51 Franklin St, Fifth Floor, Boston, MA 02110-1301 USA
#-------------------------------------------------------------------------------

"""
X11 colours for use with the Enthought Tool Suite and Graphviz.

"""

dark = [
 "indigo",
 "gold",
 "firebrick",
 "indianred",
 "darkolivegreen",
 "darkseagreen",
 "slategrey",
 "darkslategrey",
 "mediumvioletred",
 "mediumorchid",
 "chartreuse",
 "mediumslateblue",
 "black",
 "springgreen",
 "crimson",
 "brown",
 "turquoise",
 "olivedrab",
 "cyan",
 "gray",
 "darkturquoise",
 "goldenrod",
 "darkgreen",
 "darkviolet",
 "darkgray",
 "teal",
 "darkmagenta",
 "yellowgreen",
 "violet",
 "navy",
 "dimgrey",
 "orchid",
 "blue",
 "cornflowerblue",
 "darkblue",
 "darkkhaki",
 "mediumpurple",
 "red",
 "slategray",
 "darkcyan",
 "deepskyblue",
 "darkred",
 "steelblue",
 "lightslategrey",
 "mediumturquoise",
 "purple",
 "darksalmon",
 "greenyellow",
 "royalblue",
 "sienna",
 "orangered",
 "lime",
 "mediumspringgreen",
 "fuchsia",
 "peru",
 "aquamarine",
 "darkslategray",
 "dodgerblue",
 "chocolate",
 "orange",
 "forestgreen",
 "darkgrey",
 "olive",
 "darkorange",
 "cadetblue",
 "limegreen",
 "saddlebrown",
 "grey",
 "darkslateblue",
 "deeppink",
 "aqua",
 "darkgoldenrod",
 "maroon",
 "magenta",
 "rosybrown",
 "mediumseagreen",
 "slateblue",
 "dimgray",
 "seagreen",
 "mediumblue",
 "midnightblue",
 "darkorchid",
 "lawngreen",
 "hotpink",
 "mediumaquamarine",
 "green",
 "blueviolet"]

light = [
 "gold",
 "yellow",
 "mediumorchid",
 "chartreuse",
 "springgreen",
 "crimson",
 "lightsalmon",
 "turquoise",
 "cyan",
 "silver",
 "skyblue",
 "lightpink",
 "lightgoldenrodyellow",
 "lavender",
 "thistle",
 "violet",
 "ghostwhite",
 "honeydew",
 "cornsilk",
 "red",
 "bisque",
 "khaki",
 "wheat",
 "aliceblue",
 "gainsboro",
 "mediumturquoise",
 "floralwhite",
 "coral",
 "lightgrey",
 "lightcyan",
 "beige",
 "azure",
 "lightsteelblue",
 "oldlace",
 "greenyellow",
 "lightseagreen",
 "mistyrose",
 "lightcoral",
 "orangered",
 "navajowhite",
 "lime",
 "palegreen",
 "seashell",
 "mediumspringgreen",
 "fuchsia",
 "papayawhip",
 "blanchedalmond",
 "aquamarine",
 "white",
 "tomato",
 "ivory",
 "dodgerblue",
 "lemonchiffon",
 "orange",
 "forestgreen",
 "darkgrey",
 "olive",
 "mintcream",
 "antiquewhite",
 "moccasin",
 "lightskyblue",
 "deeppink",
 "aqua",
 "magenta",
 "pink",
 "lightblue",
 "palevioletred",
 "mediumseagreen",
 "powderblue",
 "snow",
 "paleturquoise",
 "palegoldenrod",
 "whitesmoke",
 "lightslategray",
 "lawngreen",
 "lightgreen",
 "lightgray",
 "hotpink",
 "lightyellow",
 "lavenderblush",
 "linen",
 "green",
 "peachpuff"
]

colours = dark + light

# EOF -------------------------------------------------------------------------
