<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="energyscheduling"
    nsURI="http:///energyscheduling.ecore" nsPrefix="energyscheduling">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This package provides the capability to schedule and account for transactions for the exchange of electric power between companies. It includes transations for megawatts which are generated, consumed, lost, passed through, sold and purchased. These classes are used by Accounting and Billing for Energy, Generation Capacity, Transmission, and Ancillary Services. "/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DynamicSchedule" eSuperTypes="iec61970.ecore#//core/RegularIntervalSchedule">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A continuously variable component of a control area's active power net interchange schedule. Dynamic schedules are sent and received by control areas."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynSchedSignRev" eType="ecore:EDataType iec61970.ecore#//domain/Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Dynamic schedule sign reversal required (yes/no)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="dynSchedStatus" eType="ecore:EDataType iec61970.ecore#//domain/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The &quot;active&quot; or &quot;inactive&quot; status of the dynamic schedule"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Receive_HostControlArea"
        lowerBound="1" eType="#//HostControlArea" eOpposite="#//HostControlArea/Receive_DynamicSchedules">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A control area can receive dynamic schedules from other control areas"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Send_HostControlArea" lowerBound="1"
        eType="#//HostControlArea" eOpposite="#//HostControlArea/Send_DynamicSchedules">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A control area can send dynamic schedules to other control areas"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Measurement" lowerBound="1"
        eType="ecore:EClass iec61970.ecore#//meas/Measurement" eOpposite="iec61970.ecore#//meas/Measurement/DynamicSchedules">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A measurement is a data source for dynamic interchange schedules"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnergyTransaction" eSuperTypes="iec61968.ecore#//documentation/documentinheritance/Document iec61970.ecore#//core/IdentifiedObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies the schedule for energy transfers between interchange areas that are necessary to satisfy the associated interchange transaction."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="firmInterchangeFlag" eType="ecore:EDataType iec61970.ecore#//domain/Boolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Firm interchange flag indicates whether or not this energy transaction can be changed without potential financial consequences."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="state" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="{ Approve | Deny | Study }"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="reason" eType="ecore:EDataType iec61970.ecore#//domain/String"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyMin" eType="ecore:EDataType iec61970.ecore#//domain/ActivePower">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Transaction minimum active power if dispatchable"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="congestChargeMax" eType="ecore:EDataType iec61970.ecore#//domain/Money">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maximum congestion charges in monetary units"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiptPointP" eType="ecore:EDataType iec61970.ecore#//domain/ActivePower">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Receipt point active power"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="deliveryPointP" eType="ecore:EDataType iec61970.ecore#//domain/ActivePower">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Delivery point active power"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Export_SubControlArea"
        lowerBound="1" eType="ecore:EClass iec61970.ecore#//core/SubControlArea" eOpposite="iec61970.ecore#//core/SubControlArea/Export_EnergyTransactions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Energy is transferred between interchange areas"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Import_SubControlArea"
        lowerBound="1" eType="ecore:EClass iec61970.ecore#//core/SubControlArea" eOpposite="iec61970.ecore#//core/SubControlArea/Import_EnergyTransactions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Energy is transferred between interchange areas"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnergyProduct" lowerBound="1"
        eType="#//EnergyProduct" eOpposite="#//EnergyProduct/EnergyTransactions">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The &quot;Source&quot; for an EnergyTransaction is an EnergyProduct which is injected into a ControlArea."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnergyProfiles" lowerBound="1"
        upperBound="-1" eType="#//EnergyProfile" eOpposite="#//EnergyProfile/EnergyTransaction">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An EnergyTransaction must have at least one EnergyProfile."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CurtailmentProfiles" upperBound="-1"
        eType="#//CurtailmentProfile" eOpposite="#//CurtailmentProfile/EnergyTransaction">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An EnergyTransaction may be curtailed by any of the participating entities."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="LossProfiles" upperBound="-1"
        eType="#//LossProfile" eOpposite="#//LossProfile/EnergyTransaction">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An EnergyTransaction may have a LossProfile."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InadvertentAccount">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An account for tracking inadvertent interchange versus time for each control area. A control area may have more than one inadvertent account in order to track inadvertent over one or more specific tie points in addition to the usual overall net inadvertent. Separate accounts would also be used to track designated time periods, such as on-peak and off-peak."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="HostControlArea" lowerBound="1"
        eType="#//HostControlArea" eOpposite="#//HostControlArea/InadvertentAccounts">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A control area can have one or more net inadvertent interchange accounts"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AreaReserveSpec">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The control area's reserve specification"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="areaReserveSpecName" eType="ecore:EDataType iec61970.ecore#//domain/String">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Identification or name of the control area's reserve specification.  A particular specification could correspond to pre-defined power system conditions, e.g., emergency situations."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="lowerRegMarginReqt" eType="ecore:EDataType iec61970.ecore#//domain/ActivePower">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Lower active power regulating margin requirement, the amount of generation that can be dropped by control in 10 minutes"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="opReserveReqt" eType="ecore:EDataType iec61970.ecore#//domain/ActivePower">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Operating active power reserve requirement, where operating reserve is the generating capability that is fully available within 30 minutes. Operating reserve is composed of primary reserve (t less than 10 min) and secondary reserve (10 less than t less than 30 min)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="primaryReserveReqt" eType="ecore:EDataType iec61970.ecore#//domain/ActivePower">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Primary active power reserve requirement, where primary reserve is generating capability that is fully available within 10 minutes. Primary reserve is composed of spinning reserve and quick-start reserve."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="raiseRegMarginReqt" eType="ecore:EDataType iec61970.ecore#//domain/ActivePower">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Raise active power regulating margin requirement, the amount of generation that can be picked up by control in 10 minutes"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="spinningReserveReqt" eType="ecore:EDataType iec61970.ecore#//domain/ActivePower">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Spinning active power reserve requirement, spinning reserve is generating capability that is presently synchronized to the network and is fully available within 10 minutes"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="HostControlAreas" upperBound="-1"
        eType="#//HostControlArea" eOpposite="#//HostControlArea/AreaReserveSpec">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A control area has one or more area reserve specifications"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ReserveEnergyTransaction"
        lowerBound="1" eType="#//Reserve" eOpposite="#//Reserve/AreaReserveSpec">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A Reserve type of energy transaction can count towards an area reserve specification."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HostControlArea" eSuperTypes="iec61970.ecore#//core/IdentifiedObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A HostControlArea has a set of tie points and a set of generator controls (i.e., AGC). It also has a total load, including transmission and distribution losses."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Controls" lowerBound="1"
        eType="ecore:EClass financial.ecore#//ControlAreaOperator" eOpposite="financial.ecore#//ControlAreaOperator/ControlledBy"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="areaControlMode" eType="#//AreaControlMode">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The area's present control mode: (CF = constant frequency) or (CTL = constant tie-line) or (TLB = tie-line bias) or (OFF = off control)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="freqSetPoint" eType="ecore:EDataType iec61970.ecore#//domain/Frequency">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The present power system frequency set point for automatic generation control"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="frequencyBiasFactor" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The control area's frequency bias factor, in active power per frequency, for automatic generation control (AGC)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="AreaReserveSpec" lowerBound="1"
        eType="#//AreaReserveSpec" eOpposite="#//AreaReserveSpec/HostControlAreas">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A control area has one or more area reserve specifications"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="InadvertentAccounts" upperBound="-1"
        eType="#//InadvertentAccount" eOpposite="#//InadvertentAccount/HostControlArea">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A control area can have one or more net inadvertent interchange accounts"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Receive_DynamicSchedules"
        upperBound="-1" eType="#//DynamicSchedule" eOpposite="#//DynamicSchedule/Receive_HostControlArea">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A control area can receive dynamic schedules from other control areas"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Send_DynamicSchedules"
        upperBound="-1" eType="#//DynamicSchedule" eOpposite="#//DynamicSchedule/Send_HostControlArea">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A control area can send dynamic schedules to other control areas"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SubControlAreas" upperBound="-1"
        eType="ecore:EClass iec61970.ecore#//core/SubControlArea" eOpposite="iec61970.ecore#//core/SubControlArea/HostControlArea">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The interchange area  may operate as a control area"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SideB_TieLines" upperBound="-1"
        eType="#//TieLine" eOpposite="#//TieLine/SideB_HostControlArea">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A HostControlArea can have zero or more tie lines."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SideA_TieLines" upperBound="-1"
        eType="#//TieLine" eOpposite="#//TieLine/SideA_HostControlArea">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A HostControlArea can have zero or more tie lines."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnergyProduct" eSuperTypes="iec61968.ecore#//core2/toplevel/Agreement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="An EnergyProduct is offered commercially as a ContractOrTariff."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="GenerationProvider" lowerBound="1"
        eType="ecore:EClass financial.ecore#//GenerationProvider" eOpposite="financial.ecore#//GenerationProvider/EnergyProducts"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnergyTransactions" lowerBound="1"
        upperBound="-1" eType="#//EnergyTransaction" eOpposite="#//EnergyTransaction/EnergyProduct">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The &quot;Source&quot; for an EnergyTransaction is an EnergyProduct which is injected into a ControlArea. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TitleHeldBy_Marketer" eType="ecore:EClass financial.ecore#//Marketer"
        eOpposite="financial.ecore#//Marketer/HoldsTitleTo_EnergyProducts">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A Marketer holds title to an EnergyProduct."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ServicePoint" lowerBound="1"
        upperBound="-1" eType="ecore:EClass reservation.ecore#//ServicePoint" eOpposite="reservation.ecore#//ServicePoint/EnergyProducts">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An EnergyProduct injects energy into a service point."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ResoldBy_Marketers" upperBound="-1"
        eType="ecore:EClass financial.ecore#//Marketer" eOpposite="financial.ecore#//Marketer/Resells_EnergyProduct">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A Marketer may resell an EnergyProduct."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnergyProfile" eSuperTypes="#//Profile">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies the start time, stop time, level for an EnergyTransaction."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TransactionBid" lowerBound="1"
        eType="ecore:EClass marketoperations.ecore#//TransactionBid" eOpposite="marketoperations.ecore#//TransactionBid/EnergyProfiles"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnergyTransaction" lowerBound="1"
        eType="#//EnergyTransaction" eOpposite="#//EnergyTransaction/EnergyProfiles">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An EnergyTransaction must have at least one EnergyProfile."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LossProfile" eSuperTypes="#//Profile">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="LossProfile is associated with an EnerrgyTransaction and must be completely contained within the time frame of the EnergyProfile associated with this EnergyTransaction."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnergyTransaction" lowerBound="1"
        eType="#//EnergyTransaction" eOpposite="#//EnergyTransaction/LossProfiles">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An EnergyTransaction may have a LossProfile."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="HasLoss_" eType="ecore:EClass financial.ecore#//TransmissionProvider"
        eOpposite="financial.ecore#//TransmissionProvider/For">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Part of the LossProfile for an EnergyTransaction may be a loss for a TransmissionProvider."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CurtailmentProfile" eSuperTypes="#//Profile">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Curtailing entity must be providing at least one service to the EnergyTransaction. The CurtailmentProfile must be completely contained within the EnergyProfile timeframe for this EnergyTransaction."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="EnergyTransaction" lowerBound="1"
        eType="#//EnergyTransaction" eOpposite="#//EnergyTransaction/CurtailmentProfiles">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="An EnergyTransaction may be curtailed by any of the participating entities."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AvailableTransmissionCapacity" eSuperTypes="iec61970.ecore#//core/Curve">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Amount of possible flow by direction."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ScheduleFor" lowerBound="1"
        upperBound="-1" eType="ecore:EClass reservation.ecore#//TransmissionService"
        eOpposite="reservation.ecore#//TransmissionService/ScheduledBy">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A transmission schedule posts the available transmission capacity for a transmission line."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TieLine">
    <eStructuralFeatures xsi:type="ecore:EReference" name="SideA_SubControlArea" lowerBound="1"
        eType="ecore:EClass iec61970.ecore#//core/SubControlArea" eOpposite="iec61970.ecore#//core/SubControlArea/SideA_TieLines">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The SubControlArea is on the A side of a collection of metered points which define the SubControlArea's boundary for a ControlAreaOperator or CustomerConsumer."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SideB_SubControlArea" lowerBound="1"
        eType="ecore:EClass iec61970.ecore#//core/SubControlArea" eOpposite="iec61970.ecore#//core/SubControlArea/SideB_TieLines">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The SubControlArea is on the B side of a collection of metered points which define the SubControlArea's boundary for a ControlAreaOperator or CustomerConsumer."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlAreaOperators" upperBound="-1"
        eType="ecore:EClass financial.ecore#//ControlAreaOperator" eOpposite="financial.ecore#//ControlAreaOperator/TieLines">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A ControlAreaOperator has a collection of tie points that ring the ControlArea, called a TieLine."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="CustomerConsumer" eType="ecore:EClass financial.ecore#//CustomerConsumer"
        eOpposite="financial.ecore#//CustomerConsumer/TieLines">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A CustomerConsumer may ring its perimeter with metering, which can create a unique SubControlArea at the collection of metering points, called a TieLine."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="DynamicEnergyTransaction"
        eType="#//Dynamic" eOpposite="#//Dynamic/TieLines">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A dynamic energy transaction can act as a pseudo tie line."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SideB_HostControlArea"
        lowerBound="1" eType="#//HostControlArea" eOpposite="#//HostControlArea/SideB_TieLines">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A HostControlArea can have zero or more tie lines."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="SideA_HostControlArea"
        lowerBound="1" eType="#//HostControlArea" eOpposite="#//HostControlArea/SideA_TieLines">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A HostControlArea can have zero or more tie lines."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransmissionCorridor" eSuperTypes="iec61970.ecore#//core/PowerSystemResource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A corridor containing one or more rights of way"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TransmissionRightOfWays"
        lowerBound="1" upperBound="-1" eType="#//TransmissionRightOfWay" eOpposite="#//TransmissionRightOfWay/TransmissionCorridor">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A transmission right-of-way is a member of a transmission corridor"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ContainedIn" upperBound="-1"
        eType="ecore:EClass reservation.ecore#//TransmissionPath" eOpposite="reservation.ecore#//TransmissionPath/For">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A TransmissionPath is contained in a TransmissionCorridor."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TransmissionRightOfWay" eSuperTypes="iec61970.ecore#//core/PowerSystemResource">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A collection of transmission lines that are close proximity to each other."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Lines" upperBound="-1"
        eType="ecore:EClass iec61970.ecore#//wires/Line" eOpposite="iec61970.ecore#//wires/Line/TransmissionRightOfWay">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A transmission line can be part of a transmission corridor"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TransmissionCorridor" lowerBound="1"
        eType="#//TransmissionCorridor" eOpposite="#//TransmissionCorridor/TransmissionRightOfWays">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A transmission right-of-way is a member of a transmission corridor"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Profile" eSuperTypes="iec61970.ecore#//core/IdentifiedObject">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A profile is a simpler curve type."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ProfileDatas" upperBound="-1"
        eType="#//ProfileData" eOpposite="#//ProfileData/Profile">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A profile has profile data associated with it."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProfileData">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Data for profile."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sequenceNumber" eType="ecore:EDataType iec61970.ecore#//domain/Integer">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Sequence to provide item numbering for the profile. { greater than or equal to 1 }"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="startDateTime" eType="ecore:EDataType iec61970.ecore#//domain/AbsoluteDateTime">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Start date/time for this profile."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="stopDateTime" eType="ecore:EDataType iec61970.ecore#//domain/AbsoluteDateTime">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Stop date/time for this profile."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="capacityLevel" eType="ecore:EDataType iec61970.ecore#//domain/ActivePower">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Active power capacity level for the profile."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="energyLevel" eType="ecore:EDataType iec61970.ecore#//domain/RealEnergy">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Energy level for the profile"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Profile" upperBound="-1"
        eType="#//Profile" eOpposite="#//Profile/ProfileDatas">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A profile has profile data associated with it."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Block" eSuperTypes="#//EnergyTransaction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A block is a simple transaction type, with no additional relationships."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Dynamic" eSuperTypes="#//EnergyTransaction">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="A dynamic energy transaction has more complex relationships than a simple block type. It behaves like a pseudo tie line."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="TieLines" upperBound="-1"
        eType="#//TieLine" eOpposite="#//TieLine/DynamicEnergyTransaction">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A dynamic energy transaction can act as a pseudo tie line."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reserve" eSuperTypes="#//EnergyTransaction">
    <eStructuralFeatures xsi:type="ecore:EReference" name="AreaReserveSpec" upperBound="-1"
        eType="#//AreaReserveSpec" eOpposite="#//AreaReserveSpec/ReserveEnergyTransaction">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="A Reserve type of energy transaction can count towards an area reserve specification."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EnergySchedulingVersion">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="version" eType="ecore:EDataType iec61970.ecore#//domain/String"
        defaultValueLiteral="EnergyScheduling_v002"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="date" eType="ecore:EDataType iec61970.ecore#//domain/AbsoluteDateTime"
        defaultValueLiteral="2007-02-07"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AreaControlMode">
    <eLiterals name="CF">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Constant frequency"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="CTL" value="1">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Constant tie-line"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TLB" value="2">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Tie-line bias"/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="OFF" value="3">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Off control"/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
</ecore:EPackage>
