<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="RAW29"
    nsURI="http://www.pti-us.com/pti/software/psse/raw" nsPrefix="raw">
  <eClassifiers xsi:type="ecore:EClass" name="Case">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ChangeCode" lowerBound="1"
        eType="#//ChangeCode" defaultValueLiteral="0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Sb" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="100">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="System base MVA for per-unit calculations."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="heading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Heading associated with the case, upto 60 characters in length."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="subheading" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Subheading associated with the case, upto 60 characters in length."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus">
    <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
      <details key="documentation" value="Network busbar."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="number" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        iD="true">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Bus number, between 1 and 99997."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="        ">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Alphanumeric identifier upto 8 characters in length, enclosed in single quotes."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseKV" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Base voltage for Bus in kV."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BusTypeCode"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Gs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Shunt conductance (MW (demanded) at V = 1.0 p.u.)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bs" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Shunt conductance (MVAr (injected) at V = 1.0 p.u.)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Area" eType="#//Area"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Zone" eType="#//Zone"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Vm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Voltage magnitude in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Va" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Voltage phase angle in degrees."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Owner" eType="#//Owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Load">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Bus" lowerBound="1" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Uppercase alphanumeric identifier upto two characters in length for distinguishing between loads at the same bus."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Is the load in-service?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Area" eType="#//Area"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Zone" eType="#//Zone"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Real power demand in MW."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Qd" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Reactive power demand in MVAr."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Active power demand in MW for constant current load."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Qi" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Reactive power demand in MVAr for constant current load."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Py" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Active power demand in MW for constant admittance load."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Qy" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Reactive power demand in MVAr for constant admittance load."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Owner" eType="#//Owner"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Bus" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Uppercase alphanumeric identifier upto two characters long for distinguishing between multiple generators at one bus."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Real power output in MW."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Qg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Reactive power output in MVAr."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Qmax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="9999">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Upper reactive power output limit in MVAr."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Qmin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="-9999">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Lower reactive power output limit in MVAr."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Vg" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Voltage magnitude setpoint in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Regulating" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="100.0">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Total MVA base for this machine, default to system base MVA."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Machine resistance in pu.u to mBase for fault analysis and dynamic simulation studies."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Xz" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Machine reactance in p.u. to mBase for fault analysis and dynamic simulation studies."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Step-up transformer resistance in p.u. to mBase."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Xt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Step-up transformer reactance in p.u. to mBase."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tapRatio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Step-up transformer off-nominal turns ration in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Is the generator in-service?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Qpct" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="100"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pmax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="9999">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Upper active power output limit in MW."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Pmin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="-9999">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Lower active power output limit in MW."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Owners" upperBound="4"
        eType="#//Owner">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Machine owners the first of which defaults to the owner of the bus."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fraction" upperBound="4"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Fraction of ownership for each owner."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="FromBus" lowerBound="1"
        eType="#//Bus">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Assumed to be the metered end."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ToBus" lowerBound="1" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="circuit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Uppercase alphanumeric identifier upto two characters in length for distinguishing between circuits between the same buses."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Line resistance in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="X" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Line reactance in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="B" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Total line charging susceptance in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="First line current rating in MVA."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateB" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Second line current rating in MVA."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateC" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Third line current rating in MVA."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Gf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Line shunt conductance at the from end in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bf" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Line shunt susceptance at the from end in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Gt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Line shunt conductance at the to end in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Line shunt susceptance at the to end in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Is the branch in-service?"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Line length in user-selected units."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Owners" upperBound="4"
        eType="#//Owner">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Line owners the first of which defaults to the owner of the from bus."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fraction" upperBound="4"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Fraction of total ownership assigned to each owner."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Transformer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="Bus1" lowerBound="1" eType="#//Bus">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="The tap ratio and phase shift angle of the transformer winding connected to the from bus may be adjusted by the power flow solution activity."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Bus2" lowerBound="1" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Bus3" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="circuit" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Uppercase alphanumeric identifier upto two characters in length for distingduishing between parallel circuits."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="windingCode" eType="#//WindingCode">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Defines the units in which V1w, V2w and V3w are specified."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="impedanceCode" eType="#//ImpedanceCode">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Defines the units in which R12, R23, R31, X12, X23 and X31 are specified."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="admittanceCode" eType="#//AdmittanceCode">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Defines the units in whcih Gm and Bm are specified."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Gm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Magnetizing conductance in units sepcified by admittanceCode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Bm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Magnetizing susceptance in units specified by admittanceCode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="NonmeteredBus" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Alphanumeric identifier in single quotes and upto eight characters in length."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="status" eType="#//TransformerStatus"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="Owners" upperBound="4"
        eType="#//Owner"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="fraction" upperBound="4"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R12" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Transformer resistance between buses 1 and 2 in units as defined by impedanceCode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="X12" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Transformer reactance between buses 1 and 2 in units as defined by impedanceCode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Sb12" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Base MVA for winding 1 to 2, defaults to the system base."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R23" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Transformer resistance between buses 2 and 3 in units as defined by impedanceCode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="X23" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Transformer reactance between buses 2 and 3 in units defined by impedanceCode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Sb23" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Base MVA for windings 2 to 3, defaults to the system base."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="R31" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Transformer resistance between windings 3 and 1 in units defined by impedanceCode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="X31" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Transformer reactance between windings 3 and 1 in units defined by impedanceCode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VmStar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Voltage magnitude at the star-point in p.u."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VaStar" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Voltage phase angle at the star-point in degrees."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="V1w" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="V1n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Va1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Winding 1 voltage phase angle in degrees."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateA1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="First rating for winding 1 in MVA."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateB1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Second rating of winding two in MVA."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateC1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Third rating for winding 3 in MVA."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="controlMode" eType="#//TransformerControlMode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ControlledBus" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rmax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rmin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Vmax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Vmin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tapPositions" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="33">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Number of available tap positions between 2 and 9999."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="impedanceTable" eType="#//TransformerImpedanceCorrectionTable"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Rc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Load drop compenstation resistance in p.u. on system base."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Xc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Load drop compensation reactance in p.u. on system base."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="V2w" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="V2n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Va2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateA2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateB2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateC2" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="V3w" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="V3n" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="Va3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateA3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateB3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rateC3" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Area"/>
  <eClassifiers xsi:type="ecore:EClass" name="Zone"/>
  <eClassifiers xsi:type="ecore:EClass" name="Owner"/>
  <eClassifiers xsi:type="ecore:EClass" name="TransformerImpedanceCorrectionTable"/>
  <eClassifiers xsi:type="ecore:EEnum" name="ChangeCode">
    <eLiterals name="BaseCase">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details value="Working case cleared before adding data."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Add" value="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details value="Data added to working case."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BusTypeCode">
    <eLiterals name="LoadBus" value="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Load bus with no generation."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="GeneratorBus" value="2">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Generator bus with fixed PV or PQ."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="SwingBus" value="3">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Reference bus."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="Isolated" value="4">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Disconnected bus."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="WindingCode">
    <eLiterals name="turnsRatio" value="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Units of V1w, V2w and V3w are the off-nominal turns ratio of winding bus base voltage in p.u."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="windingVoltage" value="2">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Units of V1w, V2w and V3w winding voltage are kV."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ImpedanceCode">
    <eLiterals name="SystemBase" value="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="In p.u. on system base quantities."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="WindingBus" value="2">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="In p.u. on specified base MVA and winding bus base voltage."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="TransformerLoadLoss" value="3">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="Transformer load loss in W."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="AdmittanceCode">
    <eLiterals name="SystemBase" value="1">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="In p.u. on system base quantities."/>
      </eAnnotations>
    </eLiterals>
    <eLiterals name="NoLoadLoss" value="2">
      <eAnnotations source="http://www.pti-us.com/pti/software/psse/documentation">
        <details key="documentation" value="No load loss in W and exciting current in p.u. on winding 1 to winding 2 base MVA and nominal voltage."/>
      </eAnnotations>
    </eLiterals>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransformerStatus">
    <eLiterals name="OutOfService"/>
    <eLiterals name="InService" value="1"/>
    <eLiterals name="WindingTwoOutOfService" value="2"/>
    <eLiterals name="WindingThreeOutOfService" value="3"/>
    <eLiterals name="WindingFourOutOfService" value="4"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TransformerControlMode">
    <eLiterals name="Fixed"/>
    <eLiterals name="VoltageControl" value="1"/>
    <eLiterals name="ReactivePowerFlow" value="2"/>
    <eLiterals name="ActivePowerFlow" value="3"/>
    <eLiterals name="DCLine" value="4"/>
  </eClassifiers>
</ecore:EPackage>
