<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Pylon"
    nsURI="http://www.pylon.org/Pylon" nsPrefix="pylon">
  <eClassifiers xsi:type="ecore:EClass" name="Case">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseMVA" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat" defaultValueLiteral="100.0"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buses" upperBound="-1"
        eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="connectedBuses" upperBound="-1"
        eType="#//Bus" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="branches" upperBound="-1"
        eType="#//Branch"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineBranches" upperBound="-1"
        eType="#//Branch" transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="generators" upperBound="-1"
        eType="#//Generator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="onlineGenerators" upperBound="-1"
        eType="#//Generator" transient="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Bus">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//busMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vBase" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="100.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vMagnitudeGuess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vAngleGuess" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="1.05"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="0.95"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pDemand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qDemand" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bShunt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="gShunt" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vMagnitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vAngle" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pLambda" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qLambda" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="muVMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="muVMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Branch">
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceBus" lowerBound="1"
        eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetBus" lowerBound="1"
        eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="online" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="r" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="x" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="b" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ratio" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="phaseShift" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="muSSource" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="muSTarget" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mode" eType="#//branchMode"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pLosses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        transient="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qLosses" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Generator">
    <eStructuralFeatures xsi:type="ecore:EReference" name="bus" eType="#//Bus"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        iD="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="online" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseMVA" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"
        defaultValueLiteral="100.0"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="p" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vMagnitude" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="q" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qMax" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qMin" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pcostModel" lowerBound="1"
        eType="#//costModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qcostModel" eType="#//costModel"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qCost" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EFloat"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="busMode">
    <eLiterals name="PV"/>
    <eLiterals name="PQ" value="1"/>
    <eLiterals name="REFERENCE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="branchMode">
    <eLiterals name="line"/>
    <eLiterals name="transformer" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="costModel">
    <eLiterals name="POLYNOMIAL"/>
    <eLiterals name="PW_LINEAR" value="1"/>
  </eClassifiers>
</ecore:EPackage>
